### ISSUE TITLE
create_gcov: Check failed: (pos + 2*width) <= buffer_ + buffer_length_

### ISSUE THREAD

**Issue by ZwjAccount** [google/autofdo#154]
./create_gcov --binary=xx --profile=perf.data --gcov=perf.afdo --gcov_version=1
E20221124 16:20:26.187492 10326 sample_reader.cc:280] No buildid found in binary
W20221124 16:20:27.157558 10326 legacy_addr2line.cc:41] File '/data/coredump/quic_server_src/build/bvc_quic_server' has no .debug_addr section.
F20221124 16:20:27.777424 10326 dwarf3ranges.cc:50] Check failed: (pos + 2*width) <= buffer_ + buffer_length_
*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by erozenfeld** [comment]
@ZwjAccount If you can you share the binary (xx) and perf.data, I can investigate.

**Comment by cjcanbibi** [comment]
I encount the same as. My binary and autofdo is compiled using gcc11.2.0. Cound u  give some advices?

> @ZwjAccount If you can you share the binary (xx) and perf.data, I can investigate.

**Comment by kingjane** [comment]
same problem

**Comment by erozenfeld** [comment]
@kingjane @cjcanbibi If you can provide your binary and perf.data (your inputs to create_gcov), I can debug the failure.

**Comment by kingjane** [comment]
> @kingjane @cjcanbibi If you can provide your binary and perf.data (your inputs to create_gcov), I can debug the failure.

Sure, here are the files.
[files.zip](https://github.com/user-attachments/files/16466635/files.zip)

**Comment by erozenfeld** [comment]
@kingjane The problem here is that the binary has DWARF5 info for some some compilation units and DWARF2 for others. That results in the binary having both `.debug_ranges` section (from DWARF2 compilation units) and `.debug_rnglists` section (from DWARF5 compilation units). The code currently expects either `.debug_ranges` section or `.debug_rnglists` section but not both. Looks like DWARF2 is coming from ../../../gcc-12.3.0/libgcc/libgcc2.c that was compiled with `-gdwarf-2` . I'll see if I can change the tool to handle binaries with both `.debug_ranges` and `.debug_rnglists` but if you can figure out how to compile libgcc2.c without `-gdwarf-2`, you'll be unblocked.

**Comment by erozenfeld** [comment]
@kingjane I made a change to handle binaries with both `.debug_ranges` and `debug_rnglst` sections: https://github.com/erozenfeld/autofdo/tree/DwarfRangeListsFix

I verified that `create_gcov` generates a gcov file for your example. I ran the tool like this:

`create_gcov -profiler perf -profile perf.data -gcov sjeng.gcov -gcov_version 2 -binary sjeng -use_lbr=0`

I'll do some more testing and open a PR.

**Comment by kingjane** [comment]
Thank you so much for your help. Your solution worked perfectly.
Yes, I built a custom GCC with the configuration: CFLAGS='-g3 -gdwarf-2' CXXFLAGS='-g3 -gdwarf-2' CFLAGS_FOR_TARGET='-g3 -gdwarf-2' CXXFLAGS_FOR_TARGET='-g3 -gdwarf-2' so that I can debug GCC. However, I'm curious why some programs compiled with this custom GCC run normally, while others fail.

> @kingjane The problem here is that the binary has DWARF5 info for some some compilation units and DWARF2 for others. That results in the binary having both `.debug_ranges` section (from DWARF2 compilation units) and `.debug_rnglists` section (from DWARF5 compilation units). The code currently expects either `.debug_ranges` section or `.debug_rnglists` section but not both. Looks like DWARF2 is coming from ../../../gcc-12.3.0/libgcc/libgcc2.c that was compiled with `-gdwarf-2` . I'll see if I can change the tool to handle binaries with both `.debug_ranges` and `.debug_rnglists` but if you can figure out how to compile libgcc2.c without `-gdwarf-2`, you'll be unblocked.

**Comment by kingjane** [comment]
Nice, I'll give it a try.
> @kingjane I made a change to handle binaries with both `.debug_ranges` and `debug_rnglst` sections: https://github.com/erozenfeld/autofdo/tree/DwarfRangeListsFix
> 
> I verified that `create_gcov` generates a gcov file for your example. I ran the tool like this:
> 
> `create_gcov -profiler perf -profile perf.data -gcov sjeng.gcov -gcov_version 2 -binary sjeng -use_lbr=0`
> 
> I'll do some more testing and open a PR.
