### ISSUE TITLE
source_info.h:56:19: error: ‘getBaseDiscriminatorFromDiscriminator’ is not a member of ‘llvm::DILocation’

### ISSUE THREAD

**Issue by blshkv** [google/autofdo#55]
sys-devel/llvm-3.9.1-r1
sys-devel/gcc-5.4.0-r3

I'm trying to compile the tool under gentoo and facing the following compilation error:
```
mv -f $depbase.Tpo $depbase.Po
depbase=`echo module_grouper.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I. -I./glog/src  -I. -I./glog/src  -std=gnu++11 -g -O2 -std=gnu++11 -MT module_grouper.o -MD -MP -MF $depbase.Tpo -c -o module_grouper.o module_grouper.cc &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo profile_creator.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I. -I./glog/src  -I. -I./glog/src  -std=gnu++11 -g -O2 -std=gnu++11 -MT profile_creator.o -MD -MP -MF $depbase.Tpo -c -o profile_creator.o profile_creator.cc &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo profile_writer.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I. -I./glog/src  -I. -I./glog/src  -std=gnu++11 -g -O2 -std=gnu++11 -MT profile_writer.o -MD -MP -MF $depbase.Tpo -c -o profile_writer.o profile_writer.cc &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo sample_reader.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I. -I./glog/src  -I. -I./glog/src  -std=gnu++11 -g -O2 -std=gnu++11 -MT sample_reader.o -MD -MP -MF $depbase.Tpo -c -o sample_reader.o sample_reader.cc &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo source_info.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I. -I./glog/src  -I. -I./glog/src  -std=gnu++11 -g -O2 -std=gnu++11 -MT source_info.o -MD -MP -MF $depbase.Tpo -c -o source_info.o source_info.cc &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo symbol_map.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I. -I./glog/src  -I. -I./glog/src  -std=gnu++11 -g -O2 -std=gnu++11 -MT symbol_map.o -MD -MP -MF $depbase.Tpo -c -o symbol_map.o symbol_map.cc &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo profile.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I. -I./glog/src  -I. -I./glog/src  -std=gnu++11 -g -O2 -std=gnu++11 -MT profile.o -MD -MP -MF $depbase.Tpo -c -o profile.o profile.cc &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo create_gcov.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I. -I./glog/src  -I. -I./glog/src  -std=gnu++11 -g -O2 -std=gnu++11 -MT create_gcov.o -MD -MP -MF $depbase.Tpo -c -o create_gcov.o create_gcov.cc &&\
mv -f $depbase.Tpo $depbase.Po
g++ -std=gnu++11 -g -O2 -std=gnu++11   -o create_gcov addr2line.o gcov.o instruction_map.o module_grouper.o profile_creator.o profile_writer.o sample_reader.o source_info.o symbol_map.o profile.o create_gcov.o libquipper.a libglog.a libsymbolize.a libgflags.a -lz -lcrypto 
depbase=`echo profile_reader.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I. -I./glog/src  -I. -I./glog/src  -std=gnu++11 -g -O2 -std=gnu++11 -MT profile_reader.o -MD -MP -MF $depbase.Tpo -c -o profile_reader.o profile_reader.cc &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo dump_gcov.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I. -I./glog/src  -I. -I./glog/src  -std=gnu++11 -g -O2 -std=gnu++11 -MT dump_gcov.o -MD -MP -MF $depbase.Tpo -c -o dump_gcov.o dump_gcov.cc &&\
mv -f $depbase.Tpo $depbase.Po
g++ -std=gnu++11 -g -O2 -std=gnu++11   -o dump_gcov profile_reader.o symbol_map.o module_grouper.o gcov.o dump_gcov.o libglog.a libgflags.a libsymbolize.a -lz -lcrypto 
depbase=`echo sample_merger.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I. -I./glog/src  -I. -I./glog/src  -std=gnu++11 -g -O2 -std=gnu++11 -MT sample_merger.o -MD -MP -MF $depbase.Tpo -c -o sample_merger.o sample_merger.cc &&\
mv -f $depbase.Tpo $depbase.Po
g++ -std=gnu++11 -g -O2 -std=gnu++11   -o sample_merger addr2line.o gcov.o instruction_map.o module_grouper.o profile_creator.o profile_writer.o sample_reader.o source_info.o symbol_map.o profile.o sample_merger.o libquipper.a libglog.a libsymbolize.a libgflags.a -lz -lcrypto 
depbase=`echo profile_merger.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I. -I./glog/src  -I. -I./glog/src  -std=gnu++11 -g -O2 -std=gnu++11 -MT profile_merger.o -MD -MP -MF $depbase.Tpo -c -o profile_merger.o profile_merger.cc &&\
mv -f $depbase.Tpo $depbase.Po
g++ -std=gnu++11 -g -O2 -std=gnu++11   -o profile_merger addr2line.o gcov.o instruction_map.o module_grouper.o profile_creator.o profile_writer.o sample_reader.o source_info.o symbol_map.o profile.o profile_reader.o profile_merger.o libquipper.a libglog.a libsymbolize.a libgflags.a -lz -lcrypto 
depbase=`echo profile_diff.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I. -I./glog/src  -I. -I./glog/src  -std=gnu++11 -g -O2 -std=gnu++11 -MT profile_diff.o -MD -MP -MF $depbase.Tpo -c -o profile_diff.o profile_diff.cc &&\
mv -f $depbase.Tpo $depbase.Po
g++ -std=gnu++11 -g -O2 -std=gnu++11   -o profile_diff addr2line.o gcov.o instruction_map.o module_grouper.o profile_creator.o profile_writer.o sample_reader.o source_info.o symbol_map.o profile.o profile_reader.o profile_diff.o libquipper.a libglog.a libsymbolize.a libgflags.a -lz -lcrypto 
depbase=`echo profile_update.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I. -I./glog/src  -I. -I./glog/src  -std=gnu++11 -g -O2 -std=gnu++11 -MT profile_update.o -MD -MP -MF $depbase.Tpo -c -o profile_update.o profile_update.cc &&\
mv -f $depbase.Tpo $depbase.Po
g++ -std=gnu++11 -g -O2 -std=gnu++11   -o profile_update addr2line.o gcov.o instruction_map.o module_grouper.o profile_creator.o profile_writer.o sample_reader.o source_info.o symbol_map.o profile.o profile_reader.o profile_update.o libquipper.a libglog.a libsymbolize.a libgflags.a -lz -lcrypto 
g++ -DHAVE_CONFIG_H -I. -I./glog/src  -I. -I./glog/src  -I/usr/include   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -g -O2 -std=gnu++11 -MT create_llvm_prof-addr2line.o -MD -MP -MF .deps/create_llvm_prof-addr2line.Tpo -c -o create_llvm_prof-addr2line.o `test -f 'addr2line.cc' || echo './'`addr2line.cc
mv -f .deps/create_llvm_prof-addr2line.Tpo .deps/create_llvm_prof-addr2line.Po
g++ -DHAVE_CONFIG_H -I. -I./glog/src  -I. -I./glog/src  -I/usr/include   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -g -O2 -std=gnu++11 -MT create_llvm_prof-gcov.o -MD -MP -MF .deps/create_llvm_prof-gcov.Tpo -c -o create_llvm_prof-gcov.o `test -f 'gcov.cc' || echo './'`gcov.cc
mv -f .deps/create_llvm_prof-gcov.Tpo .deps/create_llvm_prof-gcov.Po
g++ -DHAVE_CONFIG_H -I. -I./glog/src  -I. -I./glog/src  -I/usr/include   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -g -O2 -std=gnu++11 -MT create_llvm_prof-instruction_map.o -MD -MP -MF .deps/create_llvm_prof-instruction_map.Tpo -c -o create_llvm_prof-instruction_map.o `test -f 'instruction_map.cc' || echo './'`instruction_map.cc
mv -f .deps/create_llvm_prof-instruction_map.Tpo .deps/create_llvm_prof-instruction_map.Po
g++ -DHAVE_CONFIG_H -I. -I./glog/src  -I. -I./glog/src  -I/usr/include   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -g -O2 -std=gnu++11 -MT create_llvm_prof-module_grouper.o -MD -MP -MF .deps/create_llvm_prof-module_grouper.Tpo -c -o create_llvm_prof-module_grouper.o `test -f 'module_grouper.cc' || echo './'`module_grouper.cc
mv -f .deps/create_llvm_prof-module_grouper.Tpo .deps/create_llvm_prof-module_grouper.Po
g++ -DHAVE_CONFIG_H -I. -I./glog/src  -I. -I./glog/src  -I/usr/include   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -g -O2 -std=gnu++11 -MT create_llvm_prof-profile_creator.o -MD -MP -MF .deps/create_llvm_prof-profile_creator.Tpo -c -o create_llvm_prof-profile_creator.o `test -f 'profile_creator.cc' || echo './'`profile_creator.cc
mv -f .deps/create_llvm_prof-profile_creator.Tpo .deps/create_llvm_prof-profile_creator.Po
g++ -DHAVE_CONFIG_H -I. -I./glog/src  -I. -I./glog/src  -I/usr/include   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -g -O2 -std=gnu++11 -MT create_llvm_prof-profile_writer.o -MD -MP -MF .deps/create_llvm_prof-profile_writer.Tpo -c -o create_llvm_prof-profile_writer.o `test -f 'profile_writer.cc' || echo './'`profile_writer.cc
mv -f .deps/create_llvm_prof-profile_writer.Tpo .deps/create_llvm_prof-profile_writer.Po
g++ -DHAVE_CONFIG_H -I. -I./glog/src  -I. -I./glog/src  -I/usr/include   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -g -O2 -std=gnu++11 -MT create_llvm_prof-sample_reader.o -MD -MP -MF .deps/create_llvm_prof-sample_reader.Tpo -c -o create_llvm_prof-sample_reader.o `test -f 'sample_reader.cc' || echo './'`sample_reader.cc
mv -f .deps/create_llvm_prof-sample_reader.Tpo .deps/create_llvm_prof-sample_reader.Po
g++ -DHAVE_CONFIG_H -I. -I./glog/src  -I. -I./glog/src  -I/usr/include   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -g -O2 -std=gnu++11 -MT create_llvm_prof-source_info.o -MD -MP -MF .deps/create_llvm_prof-source_info.Tpo -c -o create_llvm_prof-source_info.o `test -f 'source_info.cc' || echo './'`source_info.cc
mv -f .deps/create_llvm_prof-source_info.Tpo .deps/create_llvm_prof-source_info.Po
g++ -DHAVE_CONFIG_H -I. -I./glog/src  -I. -I./glog/src  -I/usr/include   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -g -O2 -std=gnu++11 -MT create_llvm_prof-symbol_map.o -MD -MP -MF .deps/create_llvm_prof-symbol_map.Tpo -c -o create_llvm_prof-symbol_map.o `test -f 'symbol_map.cc' || echo './'`symbol_map.cc
mv -f .deps/create_llvm_prof-symbol_map.Tpo .deps/create_llvm_prof-symbol_map.Po
g++ -DHAVE_CONFIG_H -I. -I./glog/src  -I. -I./glog/src  -I/usr/include   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -g -O2 -std=gnu++11 -MT create_llvm_prof-profile.o -MD -MP -MF .deps/create_llvm_prof-profile.Tpo -c -o create_llvm_prof-profile.o `test -f 'profile.cc' || echo './'`profile.cc
mv -f .deps/create_llvm_prof-profile.Tpo .deps/create_llvm_prof-profile.Po
g++ -DHAVE_CONFIG_H -I. -I./glog/src  -I. -I./glog/src  -I/usr/include   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -g -O2 -std=gnu++11 -MT create_llvm_prof-llvm_profile_writer.o -MD -MP -MF .deps/create_llvm_prof-llvm_profile_writer.Tpo -c -o create_llvm_prof-llvm_profile_writer.o `test -f 'llvm_profile_writer.cc' || echo './'`llvm_profile_writer.cc
In file included from symbol_map.h:30:0,
                 from profile_writer.h:21,
                 from llvm_profile_writer.h:7,
                 from llvm_profile_writer.cc:30:
source_info.h: In member function ‘uint32 autofdo::SourceInfo::Offset(bool) const’:
source_info.h:56:19: error: ‘getBaseDiscriminatorFromDiscriminator’ is not a member of ‘llvm::DILocation’
                 ? llvm::DILocation::getBaseDiscriminatorFromDiscriminator(
                   ^
source_info.h: In member function ‘uint32 autofdo::SourceInfo::DuplicationFactor() const’:
source_info.h:66:12: error: ‘getDuplicationFactorFromDiscriminator’ is not a member of ‘llvm::DILocation’
     return llvm::DILocation::getDuplicationFactorFromDiscriminator(
            ^
llvm_profile_writer.cc: In member function ‘virtual void autofdo::LLVMProfileBuilder::VisitCallsite(const Callsite&)’:
llvm_profile_writer.cc:100:32: error: no match for ‘operator[]’ (operand types are ‘llvm::sampleprof::FunctionSamples’ and ‘llvm::StringRef’)
           line, discriminator))[CalleeName];
                                ^
make[1]: *** [Makefile:1055: create_llvm_prof-llvm_profile_writer.o] Error 1

```

**Comment by kim-phillips-arm** [comment]
Another user fixed their with-LLVM build problem by [upgrading to LLVM 4](https://groups.google.com/forum/#!topic/autofdo/lXROhLAly6k)

If that doesn't work, re-try after applying [this commit](https://github.com/kimphill/autofdo/commit/ccee2edc5b67b30d45457af36d64a1be9a31938b), after first having cleaned your autofdo directory with something like 'git ls-files -o | xargs rm'.

**Comment by blshkv** [comment]
Hi, I tried to compile with the patch and llvm3 without sucecss.

However, just upgrading LLVm (and reversing the patch) was enough.

You could specify this requirement somewhere (```configure.ac```?) probably.

**Comment by harubyy** [comment]
This is a still ongoing issue. upgrading to llvm 4 doesn't solve it. I compiled llvm4 on ubuntu xenial from source. I still get the same issue.

**Comment by kim-phillips-arm** [comment]
Hi, yes, you're right that LLVM **4** doesn't fix it: the problem is because since commit 72b7f86 "Rebase autofdo toolchain.", source_info.h uses getBaseDiscriminatorFromDiscriminator and getDuplicationFactorFromDiscriminator, which are only available in LLVM **5**:

$ find /usr/include/ -name DebugInfoMetadata.h  | xargs grep -c getDuplicationFactorFromDiscriminator
/usr/include/llvm-4.0/llvm/IR/DebugInfoMetadata.h:0
/usr/include/llvm-3.8/llvm/IR/DebugInfoMetadata.h:0
/usr/include/llvm-5.0/llvm/IR/DebugInfoMetadata.h:2

My distro (Ubuntu) allows me to have multiple LLVM versions at the same time, so I invoke llvm with an explicit version number.  Can you try installing LLVM 5 and making it the default - or try explicitly configuring autofdo to use it with something like  './configure --with-llvm=llvm-config-5.0'?

FWIW, I just pushed [a non-working, unfinished effort into forcing LLVM 5 detection](https://github.com/kim-phillips-arm/autofdo/tree/feeblefixesllvm5) ..I'll try to get back to it soon unless someone beats me to it.

**Comment by harubyy** [comment]
Hi,
Hmm, that explains why I had no problems on my archlinux. Llvm5 is the
default there. I guess I have to install llvm5 on my ubuntu server as well.
Thanks


On Jan 11, 2018 7:50 PM, "kim-phillips-arm" <notifications@github.com>
wrote:

Hi, yes, you're right that LLVM *4* doesn't fix it: the problem is because
since commit 72b7f86
<https://github.com/google/autofdo/commit/72b7f86b920a35b02faed94afc685fd2d517fc78>
"Rebase autofdo toolchain.", source_info.h uses
getBaseDiscriminatorFromDiscriminator and
getDuplicationFactorFromDiscriminator,
which are only available in LLVM *5*:

$ find /usr/include/ -name DebugInfoMetadata.h | xargs grep -c
getDuplicationFactorFromDiscriminator
/usr/include/llvm-4.0/llvm/IR/DebugInfoMetadata.h:0
/usr/include/llvm-3.8/llvm/IR/DebugInfoMetadata.h:0
/usr/include/llvm-5.0/llvm/IR/DebugInfoMetadata.h:2

My distro (Ubuntu) allows me to have multiple LLVM versions at the same
time, so I invoke llvm with an explicit version number. Can you try
installing LLVM 5 and making it the default - or try explicitly configuring
autofdo to use it with something like './configure
--with-llvm=llvm-config-5.0'?

FWIW, I just pushed a non-working, unfinished effort into forcing LLVM 5
detection
<https://github.com/kim-phillips-arm/autofdo/tree/feeblefixesllvm5> ..I'll
try to get back to it soon unless someone beats me to it.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/google/autofdo/issues/55#issuecomment-357110197>, or mute
the thread

**Comment by harubyy** [comment]
Hi again,
I installed llvm5: llvm-5.0  llvm-5.0-dev llvm-5.0-tools packages.
I issued configure with llvm: ./configure --with-llvm=llvm-config-5.0
And I get 
configure: WARNING: could not detect the LLVM libraries. Support for LLVM profiles disabled.
I modified configure to run llvm-config-5.0. I get a weird sizeof error as sen in config.log. I tried to track the compilation but I'm lost there.
[config.log](https://github.com/google/autofdo/files/1627504/config.log)

**Comment by blshkv** [comment]
FYI, it works with 4.0.1 for me, (llvm-4.0.1-r1 gentoo), but it might be something to do with additional patches:
```
        # Fix llvm-config for shared linking and sane flags
        # https://bugs.gentoo.org/show_bug.cgi?id=565358
        eapply "${FILESDIR}"/9999/0007-llvm-config-Clean-up-exported-values-update-for-shar.patch
        
        # Backport the fix for dlclose() causing option parser mess
        # e.g. https://bugs.gentoo.org/617154
        eapply "${FILESDIR}"/4.0.1/0001-cmake-Pass-Wl-z-nodelete-on-Linux-to-prevent-unloadi.patch
```

**Comment by kim-phillips-arm** [comment]
OK, here's a quick fix:

Make the following changes to ./configure (edit it manually if necessary):

diff --git a/configure b/configure
index db618a8..e0888eb 100755
--- a/configure
+++ b/configure
@@ -4889,9 +4889,11 @@ $as_echo "$ax_cv_llvm" >&6; }
       if test "x$shared_mode" = "xstatic"; then
         { $as_echo "$as_me:${as_lineno-$LINENO}: Using static LLVM libraries." >&5
 $as_echo "$as_me: Using static LLVM libraries." >&6;}
+        succeeded=yes
       elif test "x$shared_mode" = "xshared"; then
         { $as_echo "$as_me:${as_lineno-$LINENO}: Using shared LLVM libraries.  Setting -rpath to $rpath." >&5
 $as_echo "$as_me: Using shared LLVM libraries.  Setting -rpath to $rpath." >&6;}
+        succeeded=yes
       else
         as_fn_error $? "Could not determine whether to use shared or static LLVM libraries" "$LINENO" 5
       fi

Then, specifically for Ubuntu, I changed the default llvm version to 5.0 using the following commands:

sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-3.8 100
sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-5.0 1000
sudo update-alternatives --install /usr/bin/clang++ clang /usr/bin/clang-3.8 100
sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.8 100
sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-5.0 1000
sudo update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-3.8 100
sudo update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-5.0 1000

Then:

make clean
./configure --with=llvm
make -j 8

...which seemed to have worked successfully.  Can you try it and get back to us?  Thanks!

**Comment by harubyy** [comment]
it worked! I got rid of : configure: WARNING: could not detect the LLVM libraries. Support for LLVM profiles disabled. 
finally.
Bt this time, instead it was linking with llvm4 which I installed from source. I had to revert "make install":
I went to the build directory of llvm4 and issued:
sudo xargs rm < install_manifest.txt 
Then I issued configure and make as @kim-phillips-arm  suggested.
Thanks a lot!!

**Comment by kim-phillips-arm** [comment]
Hi, still trying to get to the bottom of exactly what fixes this before I continue to try to develop the configure change to e.g., require LLVM version **5** and not **4**.

From the link I quoted above back in October, i.e., in [this conversation](https://groups.google.com/forum/#!topic/autofdo/lXROhLAly6k), on 6/12/17, Brian Gesiak states "Using a build of LLVM's 4.0.0 release branch fixed the issue for me." and points us to [the output of his configure.log](https://gist.github.com/modocache/97b209b4c48e91e0e222b9f80fbfd8c7), which clearly shows it was invoked with a path to a local llvm-config:

```
./configure --with-llvm=/home/bgesiak/local/Source/llvm/install/bin/llvm-config
```
which subsequently reports it was using LLVM version 5:
```
configure:3138: /home/bgesiak/local/Source/llvm/install/bin/clang++ -v >&5
clang version 5.0.0 (http://llvm.org/git/clang.git 914763f2528905be087c1cef6597328721ba90ff) (http://llvm.org/git/llvm.git 653044e2ac52030fb912cc4510e0e83ab135573b)
```
So he was using LLVM 5, not LLVM 4.  Typo?  Let's hope that one was.

Then, blshkv commented on this issue, on Oct 3, 2017:

> Hi, I tried to compile with the patch and llvm3 without sucecss. However, just upgrading LLVm (and reversing the patch) was enough.

..yet doesn't state what version LLVM was upgraded to.

The next time blshkv comments (a few days ago), they mention the version as 4.0.1-r1 gentoo, and
that a couple of gentoo-supplied patches might be responsible for their success:

The first one, [9999/0007-llvm-config-Clean-up-exported-values-update-for-shar.patch](https://chromium.googlesource.com/chromiumos/overlays/chromiumos-overlay/+/master/sys-devel/llvm/files/9999/0007-llvm-config-Clean-up-exported-values-update-for-shar.patch) with description "Fix llvm-config for shared linking and sane flags", looks to be gentoo-specific, and whilst may help with autofdo's configure's --with-llvm=<x> documentation stating to specify <x> as the llvm-config executable (which in my last post I clearly avoided by making LLVM 5 the systemwide default, and just specified --with-llvm), it appears to be otherwise unrelated.

The second one, [0001-cmake-Pass-Wl-z-nodelete-on-Linux-to-prevent-unloadi.patch](https://archives.gentoo.org/gentoo-commits/message/ec9e3f117295218a619f07b14c5a5e04), "Backport the fix for dlclose() causing option parser mess" also appears to just change some -Wl(inker) flags, also unrelated.

Neither of them backport my findings: that in order to fix this particular issue (see title), LLVM **5**'s header files that define the missing getBaseDiscriminatorFromDiscriminator and getDuplicationFactorFromDiscriminator, need to be included to get past the problem and successfully build a 'create_llvm_prof' executable.  Currently, this happens DESPITE the configure step saying false things like:

```
configure: Using shared LLVM libraries.  Setting -rpath to /usr/lib/llvm-5.0/lib.
configure: WARNING: could not detect the LLVM libraries. Support for LLVM profiles disabled.
```

Don't worry, LLVM profiles weren't disabled, and the make step went on to successfully make a 'create_llvm_prof' executable.  One way to fix configure to not say that is to manually modify the configure script itself like I described in the last post (by adding succeeded=yes where it was missing).

So before I post a patch to autofdo's configure locking in LLVM 5 as a requirement, please can the people here help restore my sanity:

@harubyy, you said you removed an LLVM 4 installation?  Does that mean LLVM 5 was used for the final successful build?  And that was with --with-llvm but no --with-llvm=<path-to-llvm-configure>, right?

@blshkv, did you specifically get a create_llvm_prof executable without encountering the error message in the title of this bug with only LLVM 4 and ./configure --with-llvm?  Can you post your config.log so we can confirm configure was using the same version of LLVM you thought it was?  Or cut-n-paste the build log showing the g++ invocations so we can make sure it wasn't some misplaced LLVM 5 headers that were being referenced during the llvm_profile_writer.cc build step (e.g., with an extra -I/usr/lib/llvm-5.0/include)?

Thanks, confused, Kim

**Comment by blshkv** [comment]
create_llvm_prof is confirmed compiled, both build.log and config.log attached here (do not missed the second file):
https://gist.github.com/blshkv/eec27478d386bb94f7d901b660e02f67

**Comment by danielcdh** [comment]
The LLVM revision needs to include the following change:
http://llvm.org/viewvc/llvm-project?view=revision&revision=295210
which is not included in llvm4 release. So yes, you will need llvm5 in order to get discriminator support.

Please feel free to send out patch to make it less confusing/more robust.

Thanks,
Dehao

**Comment by harubyy** [comment]
Hi @kim-phillips-arm,  I have llvm5 from repo and I have llvm4 installed from source. So when I first tried your suggested solution, it was still trying to build using llvm4. I was explicitly using llvm-config-5.0:
`./configure --with-llvm=llvm-config-5.0`
and I even replaced the lines contanining llvm-config in configure with  llvm-config-5.0 after it failed. Again, no luck. I was suspicious of my $PATH since it contained /usr/local/bin before /usr/bin, so any binary related to llvm4 would be issued instead of llvm5's in configure (like in the cafe of llvm-config). To solve the problem with ease, I reverted "make install of llvm4" by  issuing: `sudo xargs rm < install_manifest.txt`
in llvm4's build folder. 
It did the trick. I was able install autofdo with llvm5 by
```
make clean
./configure --with-llvm
make -j 8
```
as you suggested. Please let me know if you need further details such as my $PATH.

**Comment by kimphill** [comment]
@harubyy, thanks for the clarification.  I get mixed results with --with-llvm=, depending on whether the absolute path was given or not (e.g., --with-llvm=`which llvm-config-5.0`), and --with-llvm is supposedly the default anyway.

@blshkv, thank you for supplying your logs, I examined them, and found -DCREATE_LLVM_PROF wasn't used when building create_llvm_prof. I'm assuming that if the binary was run, it would just say "ERROR: LLVM support was not enabled in this configuration."  This has to do with how you're running the autoconf/configure scripts, but, at least on Ubuntu, the -DCREATE_LLVM_PROF flag is passed into Makefile.in.  This also has to do with our @danielcdh maintainer not running autoconf after pulling a change to the build system (commit f7ee8285dee in this case). I'm not sure, but perhaps removing all those generated files would make more sense, maintenance-wise?

@danielcdh, I've tried to address this issue once and for all by changing the build system to not set HAVE_LLVM if the LLVM libraries don't contain getBaseDiscriminatorFromDiscriminator and getDuplicationFactorFromDiscriminator. I'll send a pull request soon, hoping after some more testing.

@all, please test this branch:

https://github.com/kim-phillips-arm/autofdo/commits/fixissue55

and let me know if I should send a pull request.

Thanks!

**Comment by blshkv** [comment]
@kimphill I was pretty sure that autoreconf and aclocal would re-create it but yes, feel free to remove auto generated files. Please also check and enforce the required version of all tools to avoid such bugs in future.

P.S. Gentoo has moved to llvm-5.0.1 by default too.

**Comment by blshkv** [comment]
I tried "fixissue55" branch but it did not fix the issue. I'm still getting:
```
configure: Using shared LLVM libraries.  Setting -rpath to /usr/lib64/llvm/5/lib64.
configure: WARNING: could not detect the LLVM (version 5 or higher) libraries. Support for LLVM profiles disabled.
```

That's probably because you applied changes to the autogenerated files. You should patch the source of it, i.e. ```ax_llvm.m4```.

I have ported these patches (see above) and that enabled it properly.

**Comment by blshkv** [comment]
btw, the second set of patches (-DCREATE_LLVM_PROF) was not really required. Profiles were enabled even without them as it seems:
```
$ ./create_llvm_prof
E0128 09:47:37.653422  8973 create_llvm_prof.cc:62] Need a name for the generated LLVM profile file.
E0128 09:47:37.653846  8973 create_llvm_prof.cc:63] Use --gcov or --out to specify an output file.
```

**Comment by kim-phillips-arm** [comment]
Hi @blshkv That ax_llvm.m4 succeeded=yes change was a hack to paper-tape over other LLVM discovery problems, like --with-llvm= being pointed to a non-absolute path (e.g., --with-llvm=llvm-config-5.0 instead of --with-llvm=), or for badness on systems with multiple LLVM version instances.

When you say "the second set of patches (-DCREATE_LLVM_PROF) was not really required", isn't that because LLVM 5 was installed?  If LLVM 4 were, create_llvm_prof would be built, but decline to run.  Please try to include config.log file contents in the future, and hopefully ones that don't contain *.ebuild affected content: bugs reported here should apply to the raw cloned git repo version of autofdo, no?

In any case, I've created a new branch, this time with the autogenerated files removed (more gentoo friendly?  not sure if @danielcdh agrees it's best but I'm sure he'll let us know), an hard dependency on LLVM 5 (or higher, anything lower will cause create_llvm_prof to decline to run), and some other fixes e.g., undefined `llvm::DisableABIBreakingChecks' linker errors by Robert Walker.  The branch is here:

https://github.com/kim-phillips-arm/autofdo/commits/fixissue55try3

Please take a look at the individual commit texts, and test (I tested on an Gentoo system running  LLVM 3.8 but not higher because I don't know how to install LLVM 4 or 5 on it). Depending on the results, I'll ask @danielcdh to pull.  Thanks for your help!

**Comment by blshkv** [comment]
yes I tested against  llvm5. As I mentioned, it went stable on gentoo recently, so I'm not going to waste anyone's time.

you can still unmask any version "echo sys-devel/llvm > /etc/portage/package.accept_keywords" and install even all 3 at the same time  by "emerge sys-devel/llvm:4" or 5, 6, or even 7 (live from the latest git)

The latest branch fixissue55try3 works fine here. It compiles and I'm able to run create_llvm_prof with profiles : 
https://gist.github.com/blshkv/f2725507aae7645b49d8e1ac56c28a61

**Comment by danielcdh** [comment]
I assume this is fixed? Please re-open if otherwise.
